services:
  app:
    build:
      context: ./
      dockerfile: docker/development/app/Dockerfile
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=contacts_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
    command: bash -c "php spark migrate && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: